name: process
version: 3.0.11
authors:
- Todd Volkert <tvolkert@google.com>
- Michael Goderbauer <goderbauer@google.com>
description: A pluggable, mockable process invocation abstraction for Dart.
homepage: https://github.com/google/process.dart

dependencies:
  file: '^5.0.0'
  intl: '>=0.14.0 <0.16.0'
  meta: ^1.1.2
  path: ^1.5.1
  platform: '>=1.0.1'

dev_dependencies:
  test: ^1.0.0

environment:
  sdk: '>=2.0.0-dev.61 <3.0.0'
