name: process
version: 4.0.0-nullsafety.2
description: A pluggable, mockable process invocation abstraction for Dart.
homepage: https://github.com/google/process.dart

environment:
  sdk: '>=2.10.0-0.0 <2.11.0'

dependencies:
  file: '^6.0.0-nullsafety.1'
  path: ^1.8.0-nullsafety
  platform: '^3.0.0-nullsafety.1'

dev_dependencies:
  test: ^1.16.0-nullsafety.1
