name: process
version: 1.0.0
authors:
- Todd Volkert <tvolkert@google.com>
description: A pluggable, mockable process invocation abstraction for Dart.
homepage: https://github.com/tvolkert/process

dependencies:
  file: ^1.0.1
  intl: '>=0.14.0 <0.15.0'
  meta: ^1.0.4
  path: ^1.4.0

dev_dependencies:
  test: ^0.12.10

environment:
  sdk: '>=1.19.0 <2.0.0'
