name: process
version: 4.0.0-nullsafety.4
description: A pluggable, mockable process invocation abstraction for Dart.
homepage: https://github.com/google/process.dart

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  file: '^6.0.0-nullsafety.4'
  path: ^1.8.0-nullsafety.3
  platform: '^3.0.0-nullsafety.4'

dev_dependencies:
  test: ^1.16.0-nullsafety.8
